# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup gradle caching
        uses: gradle/actions/setup-gradle@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: build
        shell: bash
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon build
      - name: capture build artifacts (Fabric)
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-${{ matrix.os }}
          path: |
            fabric/build/libs/*.jar
      - name: capture build artifacts (NeoForge)
        uses: actions/upload-artifact@v4
        with:
          name: NeoForge-${{ matrix.os }}
          path: |
            neoforge/build/libs/*.jar